[build]
  command = "npm_config_python=/dev/null bun install --frozen-lockfile && bun run build"
  publish = ".output/public"

[build.environment]
  NPM_FLAGS = "--version"
  NODE_VERSION = "22"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
